### ISSUE TITLE
Allow XrootD for stageout

### ISSUE THREAD

**Issue by annawoodard** [NDCMS/lobster#161]
Rumor has it that there is some way to use XrootD to send files in, not just copy them out. We should add XrootD to our stageout handling if so.

**Comment by annawoodard** [comment]
On slack, @matz-e demonstrated that this seems to be a configuration issue at ND:
```
earth: xrdcp rootlogon.C root://eoscms.cern.ch//eos/cms/store/user/matze/foo3?svcClass=default
[3.148kB/3.148kB][100%][==================================================][3.148kB/s[3.148kB/3.148kB][100%][==================================================][1.574kB/s]
earth:

matze [11:00 AM]
lxplus0017: eos
EOS Console [root://eoscms.cern.ch] |/> ls /store/user/matze
TTbarH_M-125_13TeV_amcatnlo-pythia8-tauola
foo
foo3
test_se
ttH
EOS Console [root
```

And that permission management seems to be active at CERN:
```
earth: xrdcp rootlogon.C root://eoscms.cern.ch//eos/cms/store/user/muell149/greetings_charlie?svcClass=default
[0B/0B][100%][==================================================][0B/s]
Run: [ERROR] Server responded with an error: [3010] Unable to open file /eos/cms/store/user/muell149/greetings_charlie; Operation not permitted
```

**Comment by klannon** [comment]
To be fair, all that's been demonstrated so far is that it's support at 
CERN and not ND.  We don't know yet whether ND or CERN is the more 
common case at the moment.  I guess there's rumors this is support at 
FNAL too?

**Comment by annawoodard** [comment]
I haven't tested, but [here](http://www.uscms.org/uscms_at_work/computing/setup/mass_storage.shtml) they claim it works at FNAL.

**Comment by khurtado** [comment]
@annawoodard I can confirm, I've been using xrd to copy files to FNAL via CMS-Connect...
```
[khurtado@login ~]$ hostname
login.cms.ci-connect.net
[khurtado@login ~]$ xrdcp notes root://cmseos.fnal.gov:1094//eos/uscms/store/user/kenai/tmp
[197B/197B][100%][==================================================][197B/s]  
```
```
[kenai@cmslpc37 kenai]$ hostname
cmslpc37.fnal.gov
[kenai@cmslpc37 kenai]$ ls $PWD/tmp
foo1  notes
```

**Comment by annawoodard** [comment]
Awesome. Thanks, @khurtado! Does anyone know what the relative merits of using SRM tools over XrootD are? Who knows, maybe this should be ahead of SRM on our to-do list...

**Comment by khurtado** [comment]
Considering @geoff-smith  recently overloaded deepthought with GSIFTP requests for stage-out, I think this is worth implementing.

In the past, even though `write mode` was enabled in our XRootD servers, it would refuse to write anywhere but `/hadoop/store/user/uscms01`. This shouldn't be a a problem anymore (files are always owned by `$USER` with the new grid mapping).
