### ISSUE TITLE
Lobster reporting to CMS Dashboard as an  "unknown" submission tool 

### ISSUE THREAD

**Issue by khurtado** [NDCMS/lobster#598]
Looking at the [dashboard](http://dashb-cms-jobsmry.cern.ch/dashboard/request.py/jobnumbers_individual?sites=T3_US_NotreDame&sitesSort=3&start=2017-02-28&end=2017-08-01&timeRange=daily&granularity=Daily&generic=0&sortBy=5&series=All&type=s), it seems lobster started reporting itself as an "unknown" submission tool rather than "lobster" at some point in March. 

There were many changes to [dash.py](https://github.com/matz-e/lobster/commits/master/lobster/cmssw/dash.py) that month so I guess one of those changes made that.

**Comment by klannon** [comment]
Could it be this?

https://github.com/matz-e/lobster/commit/41a5d050878414afb854d2a933bcb8b036090075#diff-44bb4af3de5f98f04b709841526f0348L163

That's the first change I found after the start of March involving telling the dashboard about "lobster").

**Comment by klannon** [comment]
There's also this:
https://github.com/matz-e/lobster/commit/2669630507a08dcdf1858ce22753d83335b960e2#diff-44bb4af3de5f98f04b709841526f0348L182

**Comment by klannon** [comment]
Also missed this one:
https://github.com/matz-e/lobster/commit/17900820868e555057529c5c3206e066374dd585#diff-44bb4af3de5f98f04b709841526f0348L144

**Comment by klannon** [comment]
OK, I'm out.  Can someone with dashboard knowledge look at those changes and suggest which, if any might explain the loss of Lobster as the tool?

**Comment by matz-e** [comment]
@klannon I have a look as soon as my projected quota for writing are satisfied with a week-long buffer again.

**Comment by matz-e** [comment]
Also, it seems like I committed this "crime"…

**Comment by klannon** [comment]
Dashboard hasn't existed for years.  Closing...
