### ISSUE TITLE
Remove all dashboard code

### ISSUE THREAD

**Issue by klannon** [NDCMS/lobster#646]
The CMS Dashboard was replaced by Monit years ago.  It's not easy to interface to Monit because the monitoring data is extracted from the glidein HTCondor classads.  Since we're not running in CMS Global Pool pilots, that doesn't work for us.  So rather than trying to replace the deprecated dashboard calls with something, I am proposing removing it entirely.

We're looking for anything that references `WMCore.Services.Dashboard.DashboardAPI`

https://github.com/NDCMS/lobster/search?q=dashboardapi

**Comment by ywan2** [comment]
A branch called `remove-dashboard` is created to implement the changes. It looks like there aren't that many things to change, or I can be mistaken. Let me know if there are any issues.
See commit [here](https://github.com/NDCMS/lobster/compare/master...remove-dashboard).

I am also wondering since CMS Dashboard was already replaced by Monit, why are other `Dashboard` codes not necessary to be removed but only ones with `DashboardAPI`?

**Comment by klannon** [comment]
Great to see that you've dived right in!

Did you test to see if you can run with the modifications you made?  It looks like you only removed some of the code that I was expecting.  For example, in the [diff](https://github.com/NDCMS/lobster/compare/master...remove-dashboard#diff-20f95ce6ae250c449d3a0c3f066de3c775284a743ca232e1a1d32d572fb3f7dcL144-L148) you referenced above, you removed line 145 from `dash.py`, but I would have said that if we're dropping dashboard support, then we should also remove line 146, and with both of those lines gone, we also don't need the `with` block at all and you could drop line 144 as well.  Then I would go and look at `patch_dash` to see if that could be dropped too.  (It seems like it should be, because it sounds like a dashboard specific piece of code.)  Then I'd also say that lines 147 and 148, plus any other lines that access `self.__dash` should also be dropped.  

Definitely anything connected with `WMCore.Services.Dashboard` should be removed, not just `DashboardAPI`.  I didn't do an exhaustive search of the code, so I'm sure there are pieces that I missed.  Don't hesitate to ask questions about anything you're unsure of.

If you get to the point where you think you've removed all the relevant code, and you're able to run @hannahbnelson's test job successfully, then please make a PR with the `lobster-with-conda` as the base branch to merge into and ask for reviews from 1-2 other people working on this code.

**Comment by klannon** [comment]
Ah, one other thing!  Can you rebase your branch to `lobster-with-conda`?  You're starting from `master`, but we want everyone to be building on the `lobster-with-conda` branch that @hannahbnelson set up.  If you're not sure how to do that, you can read the directions [here](https://stackoverflow.com/questions/14893399/rebase-feature-branch-onto-another-feature-branch), just *DON'T* delete `lobster-with-conda` at the end as the answer says.  (That answer assumes that you're using rebase to replace one branch with another, but we're eventually going to merge your branch into `lobster-with-conda`, so our case is slightly different.

**Comment by ywan2** [comment]
Thanks for the comments! I will rebase my branch and add the additional changes to test Hannah's job. It does look like if we want to remove everything related to `WMCore.Services.Dashboard`, a lot of relative things will be removed.
